# Inputs
from shiny.express import input, render, ui
import matplotlib.pyplot as plt
import numpy as np

# Generate Page Options
ui.page_opts(title='Browser Interactive App with Slider Input and Histogram Output', 
             fillable=True)

# Create Interactive Slider in a Sidebar
with ui.sidebar():
    ui.input_slider('selected_number_of_bins', 
                    'Number of Bins', 
                    0, 
                    100, 
                    20)
@render.plot(alt="Histogram Generated by Given Number of Bins")
# Function to Create Histograms
def histogram():
    # Generate Random Values for X axis
    #-> Select Seed for Consistency
    np.random.seed(123467890)

    #-> Assign 501 Random Values to X
    x = np.random.randn(501) + 10

    # Plot the Histogram
    plt.hist(x, input.selected_number_of_bins(), density = True, color='gray')
    
